spring.application.name=demo-vehical
server.port = 7898
spring.dataSource.url = jdbc:mysql://localhost:1024/vehical_db
spring.datasource.username = root
spring.datasource.password = 1234
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
